### ISSUE TITLE
Support having pages link to non-discourse pages.

### ISSUE THREAD

**Issue by mthaddon** [canonical/upload-charm-docs#26]
Having discussed with the Documentation team I've been asked to add some elements to the navigation table for the Nginx-ingress-integrator charm that are non-discourse pages. Specifically, I'm linking to the configure and actions sections of the charm's own documentation.

My reference navigation looks like this (it's a mix of both):
```
| 1 | Reference | [Reference]() |
| 2 | Actions | [Actions](https://charmhub.io/nginx-ingress-integrator/actions) |
| 2 | Configurations | [Configurations](https://charmhub.io/nginx-ingress-integrator/configure) |
| 2 | Integrations | [Integrations](/t/nginx-ingress-integrator-docs-reference-integrations/7756) |
```
Would it be possible for this project to support that somehow?

**Comment by jdkandersson** [comment]
That makes sense, I can see a few options, interested in some feedback:

1. Put these kinds of pages into the configuration file discussed in #25 
  - It would probably make more sense to have configuration files by directory in this case which would be more difficult for the user to manage
  - It means that certain pages are treated differently (some are files whilst others are just configuration)
  - It makes some logical sense since these are not pages and instead just links
2. Make them special pages, for example, requiring the first H1 to essentially be a link to something else
  - There would be logical differences between charmhub and the docs in source, i.e., a file on docs doesn't indicate a page on the server
  - Would probably be the simplest to implement
3. Add a configuration for that page, i.e., in the configuration file mark this as a special linking page
  - There would be logical differences between charmhub and the docs in source, i.e., a file on docs doesn't indicate a page on the server
4. Include an optional navigation table like structure in the `index.md` file
  - The most logical, looking in the docs directory, the index file could be read in a similar way as would appear on charmhub
  - Would need to derive a format for how this table expect to be written which should be readable in markdown as well

I think 4 sounds like the best option, this would also change how #25 #12 are implemented. I'm thinking of the following:

- Include an optional `# Contents` section in `index.md`
- It would be some sort of list of links (which are dotted or number formatted based on user preference, we should probably use some sort of markdown library for this, maybe find a way to have it executed without getting access to any secret environment variables or configurations)
- The links would be one of 3 things:
  - A local link to a directory (e.g., `[Tutorials](tutorials)` which links to the `tutorials` directory)
  - A local link to a file (e.g., `[Getting Started](tutorials/getting-started.md)` which links to the `tutorials/getting-started.md` file)
  - An external link (e.g., [Configurations](https://charmhub.io/nginx-ingress-integrator/configure))
- The link would essentially be what appears on the navigation table
- If the line is commented out, it will indicate that it should not make it on the navigation table on charmhub
- The list hierarchy indicates the level on the navigation table, this is checked against the file structure and results in an error/ warning to the user
- Files and directories don't have to be listed, if they are not listed they are injected in the appropriate location after any listed items (for backwards compatibility and easy of use) in alphabetical order

Any thoughts? @gregory-schiano as well?

**Comment by mthaddon** [comment]
I like the idea of being able to specify the `# Contents` section in `index.md`. I think practically speaking this gives you more control to be able to change ordering, etc.

**Comment by gregory-schiano** [comment]
If I understand well for Tom's example we would have something like
```
# Contents
1. [Reference]()
2. 1. [Actions](https://charmhub.io/nginx-ingress-integrator/actions)
2. 2. [Configurations](https://charmhub.io/nginx-ingress-integrator/configure)
2. 3. [Integrations](/t/nginx-ingress-integrator-docs-reference-integrations/7756)

# Navigation
| 1 | Reference |
| 2 | Actions |
| 2 | Configurations |
| 2 | Integrations |
```

If there were a `3. [Test](dir1/file1.md)`
In the content without a `|3|Dir1|
Then it would fail

And if there were a `[//]: #3. [Test](dir1/file1.md)`
Then this would be ignored because commented ?

**Comment by jdkandersson** [comment]
Not quite, for `index.md` it would be:

```markdown
# Contents

1. [Reference](reference)
  1. [Actions](https://charmhub.io/nginx-ingress-integrator/actions)
  2. [Configurations](https://charmhub.io/nginx-ingress-integrator/configure)
  3. [Integrations](reference/integrations.md)
```

Which would be translated by the action for the index page on discourse to:

```markdown
# Navigation

| level | path | navlink |
| --- | --- | --- |
| 1 | reference | [Reference]() |
| 2 |  charmhub-io-nginx-ingress-integrator-actions | [Actions](https://charmhub.io/nginx-ingress-integrator/actions) |
| 2 |  charmhub-io-nginx-ingress-integrator-configure | [Configurations](https://charmhub.io/nginx-ingress-integrator/configure) |
| 2 | reference-integrations | [Integrations](/t/nginx-ingress-integrator-docs-reference-integrations/7756) |
```

**Comment by jdkandersson** [comment]
And yes `[//]: #` will lead to a hidden element on the table. I don't like this part of the design yet, it seems weird to have to list something but it is hidden. I suppose it is a way to tell charmhub about the item

**Comment by gregory-schiano** [comment]
Ok I really like the proposal then.
What would be the max depth we would accept ?
Comments are indeed a bit strange but could be useful in some cases, won't hurt much to support that

**Comment by jdkandersson** [comment]
I hadn't considered whether we should support max depth, was just thinking of any amount of depth. Do you think there are any risks?

We can potentially use the building blocks of this library to assist with the parsing of markdown, even if the public interface is just conversion to HTML: https://github.com/Python-Markdown/markdown/blob/master/markdown/core.py It could be a little risky around relying on internal APIs, although if we pin the version and carefully consider upgrades it is probably better on balance than to implement something ourselves

**Comment by jdkandersson** [comment]
Although experimenting with it a bit doesn't seem to yield that useful results, e.g., it doesn't help very much with interpreting the list items

```Python
print(test)
# Contents

1. [Reference](reference)
  a. [Actions](https://charmhub.io/nginx-ingress-integrator/actions)
  b. [Configurations](https://charmhub.io/nginx-ingress-integrator/configure)
  c. [Integrations](reference/integrations.md)
>>> markdown.convert(test)
'<h1>Contents</h1>\n<ol>\n<li><a href="reference">Reference</a>\n  a. <a href="https://charmhub.io/nginx-ingress-integrator/actions">Actions</a>\n  b. <a href="https://charmhub.io/nginx-ingress-integrator/configure">Configurations</a>\n  c. <a href="reference/integrations.md">Integrations</a></li>\n</ol>'
```

**Comment by jdkandersson** [comment]
https://github.com/miyuchina/mistletoe produces

```markdown
# Contents

1. one
  1. one one
  2. one two
    1. one two one
    2. one two two
  3. one three
5. two
6. three
```

```Python
{
    "type": "Document",
    "footnotes": {},
    "children": [
        {"type": "Heading", "level": 1, "children": [{"type": "RawText", "content": "Contents"}]},
        {
            "type": "List",
            "children": [
                {
                    "type": "ListItem",
                    "leader": "1.",
                    "prepend": 3,
                    "children": [
                        {"type": "Paragraph", "children": [{"type": "RawText", "content": "one"}]}
                    ],
                    "loose": False,
                },
                {
                    "type": "ListItem",
                    "leader": "1.",
                    "prepend": 5,
                    "children": [
                        {
                            "type": "Paragraph",
                            "children": [{"type": "RawText", "content": "one one"}],
                        }
                    ],
                    "loose": False,
                },
                {
                    "type": "ListItem",
                    "leader": "2.",
                    "prepend": 5,
                    "children": [
                        {
                            "type": "Paragraph",
                            "children": [{"type": "RawText", "content": "one two"}],
                        }
                    ],
                    "loose": False,
                },
                {
                    "type": "ListItem",
                    "leader": "1.",
                    "prepend": 7,
                    "children": [
                        {
                            "type": "Paragraph",
                            "children": [{"type": "RawText", "content": "one two one"}],
                        }
                    ],
                    "loose": False,
                },
                {
                    "type": "ListItem",
                    "leader": "2.",
                    "prepend": 7,
                    "children": [
                        {
                            "type": "Paragraph",
                            "children": [{"type": "RawText", "content": "one two two"}],
                        }
                    ],
                    "loose": False,
                },
                {
                    "type": "ListItem",
                    "leader": "3.",
                    "prepend": 5,
                    "children": [
                        {
                            "type": "Paragraph",
                            "children": [{"type": "RawText", "content": "one three"}],
                        }
                    ],
                    "loose": False,
                },
                {
                    "type": "ListItem",
                    "leader": "5.",
                    "prepend": 3,
                    "children": [
                        {"type": "Paragraph", "children": [{"type": "RawText", "content": "two"}]}
                    ],
                    "loose": False,
                },
                {
                    "type": "ListItem",
                    "leader": "6.",
                    "prepend": 3,
                    "children": [
                        {
                            "type": "Paragraph",
                            "children": [{"type": "RawText", "content": "three"}],
                        }
                    ],
                    "loose": False,
                },
            ],
            "loose": False,
            "start": 1,
        },
    ],
}
```

**Comment by jdkandersson** [comment]
That doesn't seem that useful, a key feature we would need from a parser is to indicate that a list item is part of a grouping. I'm thinking the algorithm is pretty straight forward. The required information from each list item is (1) the hierarchy, (2) the title of the link and (2) the value of the link. The hierarchy is needed to be able to validate the structure of the list matches the structure of the directory. Any list item line is generalised to: `<whitespace><leader><reference>` where:

- `whitespace` indicates the hierarchy by the number of characters, only spaces are supported, any other whitespace here will raise an exception
- `leader` can be `(\d\.)|(\*)|(-)` (need to add in trailing whitespace into those)
- `reference ` is basically some sort of link

There would be 3 kinds of node, `file`, `link` and `directory`;

- `directory`:
  - indicated by that the reference points to a local directory (the reference must resolve to an actual directory)
  - Can be followed by any of the other items with a higher, equal or lower hierarchy
  - If it is followed by an item with a lower hierarchy, keep track of the reference for inclusion in nested checks
- `link`:
  - indicated by that the reference points to a remote host
  - Can only be followed by items at the same or lower hierarchy
- `file`:
  - Indicated by that the reference points to a local file (the reference must resolve to an actual file)
  - Can only be followed by items at the same or lower hierarchy

This is a classic recursive problem. The following data structure would keep track of items:

```Python
class ListItem(typing.NamedTuple):
    """"
    Attrs:
        hierarchy: The number of parent items to the root of the list.
        reference_title: The name of the reference
        reference_value: The link to the referenced item
        rank: The number of preceding elements in the list at any hierarchy
    """"
    hierarchy: int
    reference_title: str
    reference_value: str
    rank: int
```

Work in progress algorithm:
1. The base case is there is no new item, raise `StopIteration`
2. The non-recursive case is at a given `aggregate_directory`, `hierarchy` (defaults to `0`) and `whitespace_expectation`(defaults to the number of `whitespace` characters at the root), the current item has the same `whitespace` count as the expectation and is a `file` or `link`, yield the item
3. An error case is that the current item is a `file` or `link` at a higher `whitespace` count than the expectation, raise an exception
4. The recursive case to go one level deeper is that the current item is a `directory` at the same hierarchy, yield the item and do a recursive call incrementing the `hierarchy` and appending the `directory` to `aggregate_directory`

**Comment by jdkandersson** [comment]
We could also consider either supporting space or tab although not a mix, if we support a mix we have to assume some sort of translation from one to the other which would boost the complexity and it is generally bad practice to have a mix of space and tab. We should make sure to raise a nice error.

**Comment by jdkandersson** [comment]
I guess the maximum depth is the recursion limit in Python which I believe is 1000: https://docs.python.org/3/library/sys.html#sys.getrecursionlimit

**Comment by gregory-schiano** [comment]
What about:
https://markdown-it-py.readthedocs.io/en/latest/using.html#the-token-stream
And specifically https://markdown-it-py.readthedocs.io/en/latest/using.html#creating-a-syntax-tree

If we want to implement the algorithm, this seems to fit very well to a Tree datastructure, I don't know enough Python, are there any library or builtin type that supports Trees ? If there are the walk algorithm are already implement and probably in an efficient way.

**Comment by jdkandersson** [comment]
That library also doesn't seem to help that much, the syntax tree interprets those list items flatly:


```
print(node.pretty(indent=2, show_text=True))
<root>
  <heading>
    <inline>
      <text>
        Contents
  <ordered_list>
    <list_item>
      <paragraph>
        <inline>
          <link href='reference'>
            <text>
              Reference
    <list_item>
      <paragraph>
        <inline>
          <link href='https://charmhub.io/nginx-ingress-integrator/actions'>
            <text>
              Actions
    <list_item>
      <paragraph>
        <inline>
          <link href='https://charmhub.io/nginx-ingress-integrator/configure'>
            <text>
              Configurations
    <list_item>
      <paragraph>
        <inline>
          <link href='reference/integrations.md'>
            <text>
              Integrations
```

Also checked the tokens directly and they also interpret them as a flat list. What would be the benefits of a tree structure here? The code just needs to process the lines one by one and extract the required information, the above syntax is O(N). It doesn't need to search for items etc

**Comment by jdkandersson** [comment]
The processing of the reference is kind of nice so it could be useful for that

**Comment by jdkandersson** [comment]
The other piece is how to combine the index list with the disk list. This is maybe where a tree data structure would help, although I have been thinking about it an can't think of how it could help. The following algorithm should be O(N) as well.

We need a few data structures:

1. List of all the `PathInfo` sorted by `alphabetical_rank`
2. Iterable of `ListItem` sorted by their rank in `index.md`
3. A dictionary that has the `local_path` of the `PathInfo`s with a value of whether the item has been yielded
4. A dictionary that has the `local_path` as a key and the respective `PathInfo` as the value
5. A dictionary with all the directories of `PathInfo` and their index into the `PathInfo` list

The algorithm to get the `PathInfo` in the correct order is:

1. iterate through the `ListItem` and yield the `PathInfo` using the `local_path` to `PathInfo` lookup. That lookup can only fail for remote links which will also need to be yielded.
2. Each time a `PathInfo` is yielded, mark it off in the `local_path` to whether it has been yielded dictionary
3. Whenever a decrease in hierarchy of `ListItem` is detected, use the current directory to lookup the starting index using the directory to `PathInfo` index and yield items sequentially that have not yet been yielded whilst the `PathInfo` still has the `directory` at the start of it path, then continue yielding items based on `ListItem`
4. Yield all the remaining `PathInfo` that have not yet been yielded

**Comment by jdkandersson** [comment]
An interesting question is whether `ListItem` should have to be unique, I'm thinking not

**Comment by jdkandersson** [comment]
Spec available here: https://discourse.charmhub.io/t/specification-isc003-upload-charm-docs-contents-index-and-navigation-table/7986

**Comment by gregory-schiano** [comment]
Reviewed, and really nothing to add 💯

**Comment by arturo-seijas** [comment]
> Spec available here: https://discourse.charmhub.io/t/specification-isc003-upload-charm-docs-contents-index-and-navigation-table/7986

Looks great to me

**Comment by jdkandersson** [comment]
This has been implemented
